### ISSUE TITLE
Open Source Contribution!

### ISSUE THREAD

**Issue by thehecktour** [Nastybox/lazynite#2]
Hi, Alessio!

My name is Hector, I'm from Brazil.

I'm looking for new projects in github that I can contribute for and I found out your project and love it!!

Is it opened to receive contribution? I'd love to do this.

Regards,

**Comment by alessiocelentano** [comment]
Hi, thanks. Lazynite is a completed project, so generally it doesn't need any contribution, but if you have an idea for a feature you can develop it and do a PR.

**Comment by thehecktour** [comment]
Thanks! I do have some ideas for making the project more easy to use.
